matrix:
  include:
    - language: java
      jdk: oraclejdk17
      cache:
        yarn: true
        directories:
          - $HOME/.m2/repository
          - js/node_modules
      install: true
      script:
        - mvn -B package
    - language: node_js
      node_js: 8
      cache:
        yarn: true
        directories:
          - js/node_modules
      install: true
      script:
        - cd js
        - yarn install --frozen-lockfile
        - yarn build-prod
        - yarn flow check --max-warnings=0
